# Generated by Django 5.0.4 on 2024-05-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='status',
            field=models.IntegerField(choices=[(0, 'Submitted'), (1, 'Accepted')], default=0),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='additional_reqs',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
