# Generated by Django 5.0.4 on 2024-05-13 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookings_status_alter_bookings_additional_reqs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={'ordering': ['-submitted_on']},
        ),
    ]
